services:
  - type: web
    name: phone-enum-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false